### ISSUE TITLE
    error: could not read plugin [/home/user/.pulumi/plugins/resource-databricks-v1.16.0/pulumi-resource-databricks] stdout: EOF

### ISSUE THREAD

**Issue by freud14-tm** [pulumi/pulumi-databricks#135]
On the latest version, I get this error:
```
Previewing update (local):
     Type                            Name                                  Plan       Info
 +   pulumi:pulumi:Stack             pulumi-databricks-project-test-local  create     10 messages
     └─ pulumi:providers:databricks  default_1_16_0                                   1 error


Diagnostics:
  pulumi:pulumi:Stack (pulumi-databricks-project-test-local):
    panic: invalid alphanumeric or semver string: v1.16.0
    goroutine 1 [running]:
    github.com/databricks/databricks-sdk-go/useragent.data.With({0x0, 0x0, 0x0?}, {0x14ab41a, 0x6}, {0x16c5d18, 0x7})
        /home/runner/go/pkg/mod/github.com/databricks/databricks-sdk-go@v0.9.0/useragent/user_agent.go:95 +0x373
    github.com/databricks/databricks-sdk-go/useragent.WithUserAgentExtra(...)
        /home/runner/go/pkg/mod/github.com/databricks/databricks-sdk-go@v0.9.0/useragent/user_agent.go:45
    github.com/pulumi/pulumi-databricks/provider.Provider()
        /home/runner/work/pulumi-databricks/pulumi-databricks/provider/resources.go:47 +0x87
    main.main()
        /home/runner/work/pulumi-databricks/pulumi-databricks/provider/cmd/pulumi-resource-databricks/main.go:32 +0x2e

  pulumi:providers:databricks (default_1_16_0):
    error: could not read plugin [/home/user/.pulumi/plugins/resource-databricks-v1.16.0/pulumi-resource-databricks] stdout: EOF
```

**Comment by AaronFriel** [comment]
@freud14-tm thank you for reporting this! We're making a 1.16.1 release to resolve this.

**Comment by freud14-tm** [comment]
@AaronFriel Thank you very much.
